### ISSUE TITLE
Benchmark not correct(?)

### ISSUE THREAD

**Issue by PedroHase** [szilanor/stream#2]
When using the provided benchmark, I noticed that I could not reproduce the stated result. In my tests, this library always was the slowest.

The results of my benchmark (I added a For Loop as comparison):
```
Classic JS x 11,375,579 ops/sec ±10.54% (48 runs sampled)
Stream API x 33,607 ops/sec ±25.26% (40 runs sampled)
For loop x 34,567,827 ops/sec ±91.45% (48 runs sampled)
Fastest is For loop
```

[Online REPL](https://replit.com/@PeterHase1/szilanorstream-vs-Classic-JS-Benchmark)

Did I maybe do something wrong in my setup? If not, I think it'd be good to either remove the benchmark or update them.

**Comment by szilanor** [comment]
Duplicate #3
