### ISSUE TITLE
Use "fairer" comparison to "Classical JS"

### ISSUE THREAD

**Issue by PedroHase** [szilanor/stream#3]
The examples used for "Classical JS" seems to use code that is very slow and contains extensive typing and unneeded code.

As an example, here's a benchmark using the second to last code example (concerning readability): 
```
Map x 636 ops/sec ±124.98% (5 runs sampled)
Stream x 30,502 ops/sec ±15.18% (37 runs sampled)
Object x 441,113 ops/sec ±19.31% (34 runs sampled)
Reduce x 1,285,775 ops/sec ±5.84% (43 runs sampled)
Object with For Loop x 443,450 ops/sec ±13.82% (43 runs sampled)
Fastest is Reduce
```

As it can be seen, the map from the example is very very slow. Using an object instead of map greatly improves performance and outperforms this library (as also indicated in #2 )

[REPL with the benchmark](https://replit.com/@PeterHase1/TS-map-vs-object)

In terms of readability I'd like to suggest a more "cleaned up" comparison with less extensive typing and removing unneeded code so users can have a fair comparison between this library and "Classic JS". See following TS Playground as an example with different approaches to the problem from the example.

[Example TS Playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlmADgV1gXhgbQIwBoZ4H6EBM+AzPgCzX4CsAugNwBQLUAnogKYwAqAeQAmQgQCcAogDduYGBgDkIEQpgAfGAu4ywC1px78AStwjIANlD5deGE6DFCAPIJHjps-GGQBbAEbcYpgMAHysLAD0ETDIELwgfgBW3MDoaOkZmVnZObl5+fksoJCwYqYWUADC5gCGEBBwwABcfCZmltaGGADeLDAwykJNWAy4fTDassPBYwC+bGDcAO4wAMrcUAAUCChQAJQAdABmIJI1wAAWmwAe8iEwvf3F0DAA1twcw66ikjryMLcAKQwEjydIwAAMMAA-JpJroYMMlCpWP0ojEGmAAOYwGpyBLJVK48zmEBLCAYmBQEAwBo+RDmDgwFAQC5Ui68MrtKDjLkVap1BrATDvDgMA4sq7XPasWYytjo2K8Hw1RBggoazVa7XpIrgF58ywC+qNADqcCgFwAsqr-osVjbEC5hD8PGAvL4AkFQpt5Sx7WsNtskKhDiczpcbncHuNnrBRV8Xe4-hggSD1ZCYXCdKokYM9ON0UJkLxqezeGAalBkGUBkcYCrEBSlrwjnAxC9FtwhFSaViNuWBuYe42YFIauYS-hLbJaYgyjUexbcWAe4uezOYAHx5PuIXogFgDUlXX2VX2XAKZeG8hLrTSS2xGe5LEEDiCSkoBBeeUjbUTcA5qWo6BxxFsor4JgBzQYaVT-kKQHWqqBz9uBHx7OoGgzACDDynK4SKnEMBlMWwC2BqbBxsRv5wYKZoWhcJikbY8AhlABwkbe3CbJssEev4gQYWg9yPDAVEJvwSa-LOGDeAJT7AqCGSZrCWg5oimj5qi1HciKHzipKmxyV68r9GU1ZiHIsGyvg3SDNMowTDoDmzLiFKtDRnTcHsCrRKsUALj4MAAIIAAoAJKRAAVGJ+qlDR-mBcFiBwMMjrOm40nulunqBME9wYEcYggD4wa7D5-QSnAPCbEIl5QAgqS+hVMAHKAJKfpsWLFcgiAAEIcFGwkwFGikZlCqnwrmmkqHsc1MDAUUREAA)

**Comment by szilanor** [comment]
Updated the benchmark file with you example, added some extra operation. (benchmark/groupBy.ts).
